### ISSUE TITLE
Disable niceness for contour thresholds

### ISSUE THREAD

**Issue by domoritz** [vega/vega-geo#4] opened 2017-07-12 19:06 UTC
I want to get a single contour line none shows up

![image](https://user-images.githubusercontent.com/589034/28135290-865ea530-66fa-11e7-8e06-a37fce1c40fd.png)

**Comment by jheer** [comment] 2017-07-12 20:01
We do not perform any special processing here, we simply pass the parameter to the underlying d3-contour library. So I believe the issue is out of scope here.

See the relevant [d3-contour documentation](https://github.com/d3/d3-contour#density_thresholds) for more. Similar to tick generation, the `thresholds` method treats the input as an approximate suggestion, not a strict constraint.

**Comment by domoritz** [comment] 2017-07-12 21:20
It would be nice to be able to disable the niceness to get the exact thresholds that were requested. See https://github.com/d3/d3-contour/issues/15

**Comment by jheer** [comment] 2017-07-12 22:11
Thanks! One option would be to add a `nice` flag that controls whether we use the built-in contour generator or generate our own thresholds. If a threshold array is already provided the `nice` flag would be ignored. If so, I'm currently leaning to have the `nice` flag default to `false`. Let me know if you have any other thoughts!

**Comment by domoritz** [comment] 2017-07-12 22:14
I think that would be a useful option.

**Comment by jheer** [comment] 2017-07-13 05:52
Addressed in 20a2ee64957078f6021db49d7da557a4b812d60b: expand contour parameters to use either a `thresholds` array, or alternatively a contour `count` and optional `nice` flag.

**Closed as completed by jheer** 2017-07-13 05:52 UTC
Labels: enhancement
